AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Jobot AI

Resources:
  ########################################
  # DATABASE CONFIGURATION
  ########################################

  JobotAIConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: JobotAIConfigTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id 
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true

  ########################################
  # IAM POLICY
  ########################################
