AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Jobot AI

Parameters:
  ProxyEndpoint:
    Type: String
    Description: Proxy endpoint to pass cloudflare challenge

  ProxyApiKey:
    Type: String
    Description: Proxy API key

  AiProvider:
    Type: String
    Description: AI provider to use for the score offers
    Default: OPENAI
    AllowedValues:
      - OPENAI
      - ANTHROPIC
      - DEEPSEEK

  AiApiKey:
    Type: String
    Description: AI API key

  AiModel:
    Type: String
    Description: AI model to use
    Default: gpt-4o

  S3BucketName:
    Type: String
    Description: S3 bucket name
    Default: jobot-ai

  UserExperienceFile:
    Type: String
    Description: User experience file name
    Default: user_experience.txt

  MinScore:
    Type: String
    Description: Minimum score to consider an offer
    Default: "70"

  ResendApiKey:
    Type: String
    Description: API key for resend app to send emails

  EmailSender:
    Type: String
    Description: Email to send the offers

Resources:
  ########################################
  # DATABASE SPIDER CONFIGURATION
  ########################################

  SpiderConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SpiderConfigTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true

  ########################################
  # DATABASE SEEN OFFERS
  ########################################

  SeenOffersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SeenOffersTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: url
          AttributeType: S
      KeySchema:
        - AttributeName: url
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  ########################################
  # S3 BUCKET FOR USER EXPERIENCE
  ########################################

  JobotAIUserExperienceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ########################################
  # SPIDER LAMBDAS
  ########################################
  SharedUtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: JobotAI-SharedUtilsLayer
      Description: Shared utilities for Jobot AI
      ContentUri: src/shared/
      CompatibleRuntimes:
        - python3.14
      CompatibleArchitectures:
        - arm64

  JobotAISpiderBNEFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: JobotAI-SpiderBNEFunction
      CodeUri: src/core/spiders/bne
      Handler: index.handler
      Runtime: python3.14
      Architectures:
        - arm64
      Layers:
        - !Ref SharedUtilsLayer
      Timeout: 30
      MemorySize: 512

  JobotAISpiderLaborumFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: JobotAI-SpiderLaborumFunction
      CodeUri: src/core/spiders/laborum
      Handler: index.handler
      Runtime: python3.14
      Architectures:
        - arm64
      Layers:
        - !Ref SharedUtilsLayer
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          PROXY_ENDPOINT: !Ref ProxyEndpoint
          PROXY_API_KEY: !Ref ProxyApiKey

  JobotAISpiderGetOnBoardFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: JobotAI-SpiderGetOnBoardFunction
      CodeUri: src/core/spiders/getonboard
      Handler: index.handler
      Runtime: python3.14
      Architectures:
        - arm64
      Layers:
        - !Ref SharedUtilsLayer
      Timeout: 60
      MemorySize: 1024

  JobotAISpiderTrabajandoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: JobotAI-SpiderTrabajandoFunction
      CodeUri: src/core/spiders/trabajando
      Handler: index.handler
      Runtime: python3.14
      Architectures:
        - arm64
      Layers:
        - !Ref SharedUtilsLayer
      Timeout: 30
      MemorySize: 512

  ########################################
  # PIPELINE LAMBDAS
  ########################################

  JobotAIPipelineLoadConfigFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: JobotAI-PipelineLoadConfigFunction
      CodeUri: src/core/pipeline/load_config
      Handler: index.handler
      Runtime: python3.14
      Architectures:
        - arm64
      Timeout: 10
      MemorySize: 256
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref SpiderConfigTable
      Environment:
        Variables:
          CONFIG_TABLE: !Ref SpiderConfigTable

  JobotAIPipelineMergeOffersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: JobotAI-PipelineMergeOffersFunction
      CodeUri: src/core/pipeline/merge_offers
      Handler: index.handler
      Runtime: python3.14
      Architectures:
        - arm64
      Timeout: 30
      MemorySize: 512
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref SeenOffersTable
      Environment:
        Variables:
          SEEN_OFFERS_TABLE: !Ref SeenOffersTable

  JobotAIPipelineScoreOffersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: JobotAI-PipelineScoreOffersFunction
      CodeUri: src/core/pipeline/score_offers
      Handler: index.handler
      Runtime: python3.14
      Architectures:
        - arm64
      Timeout: 30
      MemorySize: 1024
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref SeenOffersTable
        - S3ReadPolicy:
            BucketName: !Ref S3BucketName
      Environment:
        Variables:
          SEEN_OFFERS_TABLE: !Ref SeenOffersTable
          AI_PROVIDER: !Ref AiProvider
          AI_API_KEY: !Ref AiApiKey
          AI_MODEL: !Ref AiModel
          S3_BUCKET_NAME: !Ref S3BucketName
          USER_EXPERIENCE_FILE: !Ref UserExperienceFile
          MIN_SCORE: !Ref MinScore

  JobotAIPipelineSendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: JobotAI-PipelineSendEmailFunction
      CodeUri: src/core/pipeline/send_email
      Handler: index.handler
      Runtime: python3.14
      Architectures:
        - arm64
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          RESEND_API_KEY: !Ref ResendApiKey
          EMAIL_SENDER: !Ref EmailSender

  ########################################
  # STEP FUNCTION ORCHESTRATOR (load -> spiders -> filter-batch -> score -> send email)
  ########################################

  JobotAIOrchestrator:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: JobotAI-Orchestrator
      Definition:
        Comment: "Load config -> spiders dynamically -> filter-batch results -> score offers -> send email"
        StartAt: LoadConfig
        TimeoutSeconds: 60
        States:
          LoadConfig:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            OutputPath: $.Payload
            Parameters:
              FunctionName: !Ref JobotAIPipelineLoadConfigFunction
              Payload: {}
            Next: RunSpiders

          RunSpiders:
            Type: Map
            ItemsPath: $.spiders
            MaxConcurrency: 5
            Iterator:
              StartAt: InvokeSpider
              States:
                InvokeSpider:
                  Type: Task
                  Resource: arn:aws:states:::lambda:invoke
                  OutputPath: $.Payload
                  Parameters:
                    FunctionName.$: $.lambda_name
                    Payload:
                      config.$: $.config
                  End: true
            Next: MergeOffers

          MergeOffers:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            OutputPath: $.Payload
            Parameters:
              FunctionName: !Ref JobotAIPipelineMergeOffersFunction
              Payload:
                offers.$: $
            Next: CheckIfEmpty

          CheckIfEmpty:
            Type: Choice
            Choices:
              - Variable: $.batches
                IsPresent: false
                Next: EndExecution
              - Variable: $.batches
                IsNull: true
                Next: EndExecution
            Default: RunBatches

          RunBatches:
            Type: Map
            ItemsPath: $.batches
            MaxConcurrency: 5
            Iterator:
              StartAt: InvokeBatch
              States:
                InvokeBatch:
                  Type: Task
                  Resource: arn:aws:states:::lambda:invoke
                  OutputPath: $.Payload
                  Parameters:
                    FunctionName: !Ref JobotAIPipelineScoreOffersFunction
                    Payload:
                      batch.$: $
                  End: true
            Next: SendEmail

          SendEmail:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Parameters:
              FunctionName: !Ref JobotAIPipelineSendEmailFunction
              Payload:
                new_offers.$: $
            Next: EndExecution

          EndExecution:
            Type: Succeed

      Role: !GetAtt JobotAIOrchestratorRole.Arn

  ########################################
  # EVENT BRIDGE SCHEDULE TRIGGER
  ########################################

  JobotAIScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: JobotAI-ScheduleTrigger
      Description: Schedule trigger for JobotAI orchestrator at specific hours daily
      ScheduleExpression: cron(0 11,15,19,23 * * ? *)
      State: ENABLED
      Targets:
        - Arn: !Ref JobotAIOrchestrator
          RoleArn: !GetAtt JobotAIEventBridgeStepRole.Arn
          Id: JobotAI-OrchestratorTarget

  ########################################
  # IAM ROLES
  ########################################

  JobotAIOrchestratorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFnLambdaInvokePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"

  JobotAIEventBridgeStepRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StartStepFunctionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !Ref JobotAIOrchestrator
